version: '3'
services:
    node:
        image: node:17-alpine
        container_name: react-project
        working_dir: /app
        volumes:
            - ./:/app     
        command: npm start
        ports:
            - "3000:3000" 
